/* ================================================================
   SUKOON — script.js
   To add/remove songs and shayaris, use admin.html — it generates
   the exact code block to paste in here. You should not need to
   edit this file by hand except to paste that generated block.
================================================================= */

/* ================================================================
   SHAYARIS — generated by admin.html, paste replacement array here
================================================================= */
const shayaris = [
  "ek shor hai mujhme, jo khamosh bahut hai",
  "Kaun seekha hai sirf baaton se, sabko ek haadsa zaroori hai",
  "Aankhein thi jo keh gayi sab kuch, Lafz hote toh mukar gaye hote",
  "Tu azaad hai mujhe kaid karke, Main kaid hun tujhe azaad karke",
  "Mujhko mujh mein jagah nahi milti, Tu hai maujood is qadar mujh mein",
  "Khamoshi tum samajh nahi rahe, alfaaz ab bachey nahin",
  "Maine parkha hai apni badkismati ko, Main jisse apna keh du wo mera nahi rehta",
  "jo naseeb mein hai, woh chal kar aayega, jo nahin hai, woh aa kar bhi chala jayega",
  "wo laut kar aya hai manane ko, shayad azma kar aya hai zamane ko",
  "Itna kareeb ho gaya tha, mujhe laga mera ho gaya tha",
  "Badnaam toh bohot hun iss zamane mein, Tu bata tere sunne me konsa kissa aaya hai",
  "Tabah hokar bhi tabahi nahi dikhti, Yeh ishq hai hazoor iski koi davai nahi bikti",
  "Jab rehna hai tanha toh rona kaisa, jo tha hi nahi apna usey khona kaisa",
  "dard sabka hai yahan, koi likh raha hai, toh koi padh raha hai"
];
let sIndex = 0;
const shayariEl = document.getElementById('shayariLine');
function showShayari() {
  shayariEl.classList.remove('show');
  setTimeout(() => {
    shayariEl.innerHTML = shayaris[sIndex % shayaris.length];
    shayariEl.classList.add('show');
    sIndex++;
  }, 500);
}
showShayari();
setInterval(showShayari, 8000);

/* ================================================================
   FIREBASE SETUP
   Replace the values below with YOUR OWN config from the Firebase
   console (Project settings > General > Your apps). See the setup
   guide for exact steps — this is a one-time, free setup.
================================================================= */
const firebaseConfig = {
  apiKey: "AIzaSyCjsP-50WtwtXp9-ecFz2gN-nlXv7cOUrs",
  authDomain: "sukoon-1f380.firebaseapp.com",
  databaseURL: "https://sukoon-1f380-default-rtdb.firebaseio.com",
  projectId: "sukoon-1f380",
  storageBucket: "sukoon-1f380.firebasestorage.app",
  messagingSenderId: "1031908409160",
  appId: "1:1031908409160:web:57bb7839b090d93f377d7d"
};

firebase.initializeApp(firebaseConfig);
const db = firebase.database();

/* ---------- REAL LIVE LISTENER COUNT ----------
   Every visitor adds one entry to /presence while their tab is open.
   The entry is automatically removed the moment they close the tab
   or lose connection, so the count is always exact — never guessed. */
const presenceRef = db.ref('presence');
const myPresenceRef = presenceRef.push();
myPresenceRef.set(true);
myPresenceRef.onDisconnect().remove();

const countEl = document.getElementById('listenerCount');
presenceRef.on('value', (snapshot) => {
  countEl.textContent = snapshot.numChildren();
});

/* ---------- LIVE CLOCK ---------- */
const clockEl = document.getElementById('clockDisplay');
function updateClock() {
  const now = new Date();
  let h = now.getHours();
  const m = now.getMinutes().toString().padStart(2, '0');
  const ampm = h >= 12 ? 'PM' : 'AM';
  h = h % 12;
  if (h === 0) h = 12;
  clockEl.textContent = `${h}:${m} ${ampm}`;
}
updateClock();
setInterval(updateClock, 1000);

/* ================================================================
   PLAYLIST — generated by admin.html, paste replacement array here
   id = the YouTube video ID (the part after "v=" in the video URL)
================================================================= */
const playlist = [
  { id: "oafxkMv4xnc", title: "Bairan", artist: "Banjaare" },
  { id: "ebZj_nrmH-c", title: "Barsaat", artist: "Banjaare" },
  { id: "1uypbHj8-Mk", title: "KITAB", artist: "Mr Dutt ft Vipin Foji | Tanu Rawat" },
  { id: "l1pHRTFkKKs", title: "Khat", artist: "Navjot Ahuja" },
  { id: "BfM86k78AO0", title: "Parwaaz", artist: "Farak" },
  { id: "EiiOYwqk3A0", title: "FAASLE", artist: "Aditya Rikhari" },
  { id: "nufpHIRA6CM", title: "Malaal", artist: "Yuvi" },
  { id: "QxddU3sjVRY", title: "Shikayat", artist: "AUR" },
  { id: "kz0kbFmB7FU", title: "The Last Letter", artist: "Maan Panu" },
  { id: "pK6Cit3BoRQ", title: "Kyun Dhunde", artist: "Vilen" }
];
let currentTrack = 0;
let player;
let isPlaying = false;

const playBtn = document.getElementById('playBtn');
const playIcon = document.getElementById('playIcon');
const prevBtn = document.getElementById('prevBtn');
const nextBtn = document.getElementById('nextBtn');
const songbar = document.getElementById('songbar');
const trackNameEl = document.getElementById('trackName');
const artistNameEl = document.getElementById('artistName');
const progressFill = document.getElementById('progressFill');
const progressBar = document.getElementById('progressBar');
const curTimeEl = document.getElementById('curTime');
const durTimeEl = document.getElementById('durTime');

const tag = document.createElement('script');
tag.src = "https://www.youtube.com/iframe_api";
document.head.appendChild(tag);

/* ================================================================
   RESUME EXACTLY WHERE THE VISITOR LEFT OFF
   Remembers which song AND the exact second, per visitor's browser —
   like Spotify. Saved a few times a second while playing, and once
   more when the tab is closed, so nothing is lost.
================================================================= */
const savedTrack = parseInt(localStorage.getItem('sukoon_lastTrack'), 10);
const savedTime = parseFloat(localStorage.getItem('sukoon_lastTime'));
let pendingResumeTime = 0;

if (!isNaN(savedTrack) && savedTrack >= 0 && savedTrack < playlist.length) {
  currentTrack = savedTrack;
  if (!isNaN(savedTime) && savedTime > 0) {
    pendingResumeTime = savedTime;
  }
}

function saveProgress() {
  localStorage.setItem('sukoon_lastTrack', currentTrack);
  if (player && player.getCurrentTime) {
    const t = player.getCurrentTime();
    if (t > 0) localStorage.setItem('sukoon_lastTime', t);
  }
}
window.addEventListener('pagehide', saveProgress);
window.addEventListener('beforeunload', saveProgress);

/* ================================================================
   SHUFFLE
================================================================= */
let isShuffle = false;
let shuffleHistory = [];
const shuffleBtn = document.getElementById('shuffleBtn');

function pickRandomIndex(excludeIndex) {
  if (playlist.length <= 1) return excludeIndex;
  let idx;
  do {
    idx = Math.floor(Math.random() * playlist.length);
  } while (idx === excludeIndex);
  return idx;
}

if (shuffleBtn) {
  shuffleBtn.addEventListener('click', () => {
    isShuffle = !isShuffle;
    shuffleBtn.classList.toggle('active', isShuffle);
    shuffleHistory = [];
  });
}

function onYouTubeIframeAPIReady() {
  player = new YT.Player('player', {
    height: '0',
    width: '0',
    videoId: playlist[currentTrack].id,
    playerVars: { autoplay: 0, controls: 0 },
    events: {
      onStateChange: onPlayerStateChange,
      onReady: () => {
        updateTrackInfo();
        if (pendingResumeTime > 0) {
          player.seekTo(pendingResumeTime, true);
          pendingResumeTime = 0;
        }
      }
    }
  });
}

function updateTrackInfo() {
  trackNameEl.textContent = playlist[currentTrack].title;
  artistNameEl.textContent = playlist[currentTrack].artist || '';
}

function loadTrack(index, autoplay, seekSeconds) {
  if (playlist[index].id === "REPLACE_WITH_VIDEO_ID") {
    alert("This slot is empty — use admin.html to generate the code and paste it into script.js.");
    return;
  }
  currentTrack = index;
  updateTrackInfo();
  if (player && player.loadVideoById) {
    if (autoplay) {
      player.loadVideoById(playlist[currentTrack].id, seekSeconds || 0);
    } else {
      player.cueVideoById(playlist[currentTrack].id, seekSeconds || 0);
    }
  }
}

/* ---------- reliable click-ring feedback on the buttons ---------- */
function ringEffect(btn) {
  btn.classList.remove('pulse');
  void btn.offsetWidth; // forces the browser to acknowledge the removal so the animation can replay
  btn.classList.add('pulse');
}

playBtn.addEventListener('click', () => {
  ringEffect(playBtn);
  if (!player) return;
  if (isPlaying) {
    player.pauseVideo();
  } else {
    if (playlist[currentTrack].id === "REPLACE_WITH_VIDEO_ID") {
      alert("This slot is empty — use admin.html to generate the code and paste it into script.js.");
      return;
    }
    player.playVideo();
  }
});

prevBtn.addEventListener('click', () => {
  ringEffect(prevBtn);
  if (isShuffle && shuffleHistory.length > 0) {
    const prevIndex = shuffleHistory.pop();
    loadTrack(prevIndex, isPlaying);
  } else if (isShuffle) {
    loadTrack(pickRandomIndex(currentTrack), isPlaying);
  } else {
    const newIndex = (currentTrack - 1 + playlist.length) % playlist.length;
    loadTrack(newIndex, isPlaying);
  }
});

nextBtn.addEventListener('click', () => {
  ringEffect(nextBtn);
  if (isShuffle) {
    shuffleHistory.push(currentTrack);
    loadTrack(pickRandomIndex(currentTrack), isPlaying);
  } else {
    const newIndex = (currentTrack + 1) % playlist.length;
    loadTrack(newIndex, isPlaying);
  }
});

function onPlayerStateChange(event) {
  if (event.data === YT.PlayerState.PLAYING) {
    isPlaying = true;
    songbar.classList.add('playing');
    playIcon.innerHTML = '<path d="M6 5h4v14H6zM14 5h4v14h-4z"/>';
  } else if (event.data === YT.PlayerState.PAUSED) {
    isPlaying = false;
    songbar.classList.remove('playing');
    playIcon.innerHTML = '<path d="M8 5v14l11-7z"/>';
  } else if (event.data === YT.PlayerState.ENDED) {
    if (isShuffle) {
      shuffleHistory.push(currentTrack);
      loadTrack(pickRandomIndex(currentTrack), true);
    } else {
      const newIndex = (currentTrack + 1) % playlist.length;
      loadTrack(newIndex, true);
    }
  }
}

/* ---------- time formatting ---------- */
function formatTime(seconds) {
  if (!isFinite(seconds) || seconds < 0) return '0:00';
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60).toString().padStart(2, '0');
  return `${m}:${s}`;
}

/* ---------- progress bar: shows real time, and is fully seekable
   by tapping or dragging anywhere on it ---------- */
let isSeeking = false;

function seekFromPointer(clientX) {
  if (!player || !player.getDuration) return;
  const rect = progressBar.getBoundingClientRect();
  let fraction = (clientX - rect.left) / rect.width;
  fraction = Math.min(Math.max(fraction, 0), 1);
  const duration = player.getDuration();
  if (duration > 0) {
    player.seekTo(duration * fraction, true);
    progressFill.style.width = (fraction * 100) + '%';
    curTimeEl.textContent = formatTime(duration * fraction);
  }
}

progressBar.addEventListener('pointerdown', (e) => {
  isSeeking = true;
  seekFromPointer(e.clientX);
});
window.addEventListener('pointermove', (e) => {
  if (isSeeking) seekFromPointer(e.clientX);
});
window.addEventListener('pointerup', () => {
  isSeeking = false;
});

setInterval(() => {
  if (player && player.getCurrentTime && !isSeeking) {
    const dur = player.getDuration();
    const cur = player.getCurrentTime();
    if (dur > 0) {
      progressFill.style.width = (cur / dur * 100) + '%';
      curTimeEl.textContent = formatTime(cur);
      durTimeEl.textContent = formatTime(dur);
      localStorage.setItem('sukoon_lastTrack', currentTrack);
      localStorage.setItem('sukoon_lastTime', cur);
    }
  }
}, 500);
