/* ================================================================
   SUKOON — script.js
   To add/remove songs and shayaris, use admin.html — it generates
   the exact code block to paste in here. You should not need to
   edit this file by hand except to paste that generated block.
================================================================= */

/* ================================================================
   SHAYARIS — generated by admin.html, paste replacement array here
================================================================= */
const shayaris = [
  "har raat guzar jaati hai,<br>kuch gaane saath reh jaate hain",
  "akele hone mein bhi ek sukoon hai,<br>khud se milne ka mausam hai",
  "khamoshi bhi kabhi kabhi<br>sabse achhi dost lagti hai",
  "chaand akela nahi hota,<br>bas thoda door hota hai",
  "kuch log akele nahi hote,<br>bas apne saath hote hain"
];

let sIndex = 0;
const shayariEl = document.getElementById('shayariLine');
function showShayari() {
  shayariEl.classList.remove('show');
  setTimeout(() => {
    shayariEl.innerHTML = shayaris[sIndex % shayaris.length];
    shayariEl.classList.add('show');
    sIndex++;
  }, 500);
}
showShayari();
setInterval(showShayari, 8000);

/* ================================================================
   FIREBASE SETUP
   Replace the values below with YOUR OWN config from the Firebase
   console (Project settings > General > Your apps). See the setup
   guide for exact steps — this is a one-time, free setup.
================================================================= */
const firebaseConfig = {
  apiKey: "AIzaSyCjsP-50WtwtXp9-ecFz2gN-nlXv7cOUrs",
  authDomain: "sukoon-1f380.firebaseapp.com",
  databaseURL: "https://sukoon-1f380-default-rtdb.firebaseio.com",
  projectId: "sukoon-1f380",
  storageBucket: "sukoon-1f380.firebasestorage.app",
  messagingSenderId: "1031908409160",
  appId: "1:1031908409160:web:57bb7839b090d93f377d7d"
};
firebase.initializeApp(firebaseConfig);
const db = firebase.database();

/* ---------- REAL LIVE LISTENER COUNT ----------
   Every visitor adds one entry to /presence while their tab is open.
   The entry is automatically removed the moment they close the tab
   or lose connection, so the count is always exact — never guessed. */
const presenceRef = db.ref('presence');
const myPresenceRef = presenceRef.push();
myPresenceRef.set(true);
myPresenceRef.onDisconnect().remove();

const countEl = document.getElementById('listenerCount');
presenceRef.on('value', (snapshot) => {
  countEl.textContent = snapshot.numChildren();
});

/* ---------- LIVE CLOCK ---------- */
const clockEl = document.getElementById('clockDisplay');
function updateClock() {
  const now = new Date();
  let h = now.getHours();
  const m = now.getMinutes().toString().padStart(2, '0');
  const ampm = h >= 12 ? 'PM' : 'AM';
  h = h % 12;
  if (h === 0) h = 12;
  clockEl.textContent = `${h}:${m} ${ampm}`;
}
updateClock();
setInterval(updateClock, 1000);

/* ================================================================
   PLAYLIST — generated by admin.html, paste replacement array here
   id = the YouTube video ID (the part after "v=" in the video URL)
================================================================= */
const playlist = [
  { id: "ebZj_nrmH-c", title: "Barsaat", artist: "Banjaare" },
  { id: "oafxkMv4xnc", title: "Bairan", artist: "Banjaare" },
  { id: "U0EI7XFkkV4", title: "Taare", artist: "Farak" },
  { id: "1uypbHj8-Mk", title: "KITAB", artist: "Mr Dutt ft Vipin Foji | Tanu Rawat" }
];

let currentTrack = 0;
let player;
let isPlaying = false;

const playBtn = document.getElementById('playBtn');
const playIcon = document.getElementById('playIcon');
const prevBtn = document.getElementById('prevBtn');
const nextBtn = document.getElementById('nextBtn');
const songbar = document.getElementById('songbar');
const trackNameEl = document.getElementById('trackName');
const artistNameEl = document.getElementById('artistName');
const progressFill = document.getElementById('progressFill');

const tag = document.createElement('script');
tag.src = "https://www.youtube.com/iframe_api";
document.head.appendChild(tag);

function onYouTubeIframeAPIReady() {
  player = new YT.Player('player', {
    height: '0',
    width: '0',
    videoId: playlist[currentTrack].id,
    playerVars: { autoplay: 0, controls: 0 },
    events: {
      onStateChange: onPlayerStateChange,
      onReady: () => { updateTrackInfo(); }
    }
  });
}

function updateTrackInfo() {
  trackNameEl.textContent = playlist[currentTrack].title;
  artistNameEl.textContent = playlist[currentTrack].artist || '';
}

function loadTrack(index, autoplay) {
  if (playlist[index].id === "REPLACE_WITH_VIDEO_ID") {
    alert("This slot is empty — use admin.html to generate the code and paste it into script.js.");
    return;
  }
  currentTrack = index;
  updateTrackInfo();
  if (player && player.loadVideoById) {
    if (autoplay) {
      player.loadVideoById(playlist[currentTrack].id);
    } else {
      player.cueVideoById(playlist[currentTrack].id);
    }
  }
}

playBtn.addEventListener('click', () => {
  if (!player) return;
  if (isPlaying) {
    player.pauseVideo();
  } else {
    if (playlist[currentTrack].id === "REPLACE_WITH_VIDEO_ID") {
      alert("This slot is empty — use admin.html to generate the code and paste it into script.js.");
      return;
    }
    player.playVideo();
  }
});

prevBtn.addEventListener('click', () => {
  const newIndex = (currentTrack - 1 + playlist.length) % playlist.length;
  loadTrack(newIndex, isPlaying);
});

nextBtn.addEventListener('click', () => {
  const newIndex = (currentTrack + 1) % playlist.length;
  loadTrack(newIndex, isPlaying);
});

function onPlayerStateChange(event) {
  if (event.data === YT.PlayerState.PLAYING) {
    isPlaying = true;
    songbar.classList.add('playing');
    playIcon.innerHTML = '<path d="M6 5h4v14H6zM14 5h4v14h-4z"/>';
  } else if (event.data === YT.PlayerState.PAUSED) {
    isPlaying = false;
    songbar.classList.remove('playing');
    playIcon.innerHTML = '<path d="M8 5v14l11-7z"/>';
  } else if (event.data === YT.PlayerState.ENDED) {
    const newIndex = (currentTrack + 1) % playlist.length;
    loadTrack(newIndex, true);
  }
}

setInterval(() => {
  if (player && player.getCurrentTime && isPlaying) {
    const dur = player.getDuration();
    const cur = player.getCurrentTime();
    if (dur > 0) {
      progressFill.style.width = (cur / dur * 100) + '%';
    }
  }
}, 1000);
